const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
let timer=null,learnTimer=null,discoverTimer=null,metadata=[],lastAlertKey=null;
async function call(path,opts={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function msg(text,bad=false){const e=document.getElementById("msg");e.textContent=text;e.className=bad?"bad":"good"}
function saveSettings(){localStorage.setItem("torntools.v04.settings",JSON.stringify({interval:interval.value,minProfit:minProfit.value,minRoi:minRoi.value,stockDiscount:stockDiscount.value,sound:sound.checked,watched:[...document.querySelectorAll(".watch-toggle")].filter(x=>x.checked).map(x=>Number(x.value))}))}
function loadSavedSettings(){try{const s=JSON.parse(localStorage.getItem("torntools.v04.settings")||localStorage.getItem("torntools.v03.settings")||localStorage.getItem("torntools.v02.settings")||"{}");if(s.interval)interval.value=s.interval;if(s.minProfit!==undefined)minProfit.value=s.minProfit;if(s.minRoi!==undefined)minRoi.value=s.minRoi;if(s.stockDiscount!==undefined)stockDiscount.value=s.stockDiscount;if(s.sound!==undefined)sound.checked=!!s.sound;return Array.isArray(s.watched)?s.watched:null}catch{return null}}
async function status(){try{const d=await call("/api/status");metadata=d.items||[];const e=document.getElementById("status");e.textContent=d.key_loaded?`● V${d.version} · key loaded`:`● V${d.version} · key needed`;e.className=d.key_loaded?"pill good":"pill warn";renderWatchlist();await loadLiquidity()}catch{const e=document.getElementById("status");e.textContent="Backend unavailable";e.className="pill bad"}}
function renderWatchlist(){const h=watchlist,s=loadSavedSettings();h.innerHTML="";metadata.forEach(i=>{const c=s?s.includes(i.id):i.enabled;h.insertAdjacentHTML("beforeend",`<label class="watch-chip ${i.mode}"><input class="watch-toggle" type="checkbox" value="${i.id}" ${c?"checked":""} onchange="watchChanged()"><span class="watch-name">${i.name}</span><span class="mode-tag">${i.mode==="stock"?"PERSONAL USE":"RESALE"}</span><small>${i.note}</small></label>`)});watchChanged(false)}
function watchChanged(save=true){watchingCount.textContent=document.querySelectorAll(".watch-toggle:checked").length;if(save)saveSettings()}
async function loadKey(){const k=key.value.trim();if(!k)return msg("Paste a key first.",true);try{loadKeyBtn.disabled=true;msg("Loading key…");const r=await call("/api/key",{method:"POST",body:JSON.stringify({api_key:k})});key.value="";msg(r.message||"Key loaded.");await status();await scanNow()}catch(e){msg(e.message,true)}finally{loadKeyBtn.disabled=false}}
async function forgetKey(){try{await call("/api/key",{method:"DELETE"});msg("Key forgotten.");stopAuto();stopLearnAuto();stopDiscoverAuto();await status()}catch(e){msg(e.message,true)}}
function selectedIds(){return[...document.querySelectorAll(".watch-toggle:checked")].map(x=>x.value)}
function isDeal(i){if(i.error)return false;if(i.mode==="stock")return Number(i.discount_pct||0)>=Number(stockDiscount.value||0);return Number(i.floor_clear_profit_after_fee||0)>=Number(minProfit.value||0)&&Number(i.net_roi_after_fee||0)>=Number(minRoi.value||0)}
function score(i){if(i.error)return-999;if(i.mode==="stock")return Number(i.discount_pct||0)*10;return Math.max(0,Number(i.net_roi_after_fee||0)*8+Number(i.floor_clear_profit_after_fee||0)/50000)}
function card(i){if(i.error)return`<article class="deal-card error-card"><div class="card-top"><div><h3>${i.name}</h3><span class="mode-tag">ERROR</span></div></div><p>${i.error}</p></article>`;const d=isDeal(i),p=i.mode==="stock",disc=Number(i.discount_pct||0),profit=Number(i.floor_clear_profit_after_fee||0),roi=Number(i.net_roi_after_fee||0);return`<article class="deal-card ${d?"deal":""}"><div class="card-top"><div><h3>${i.name}</h3><span class="mode-tag">${p?"PERSONAL USE":"RESALE"}</span></div><span class="deal-badge">${d?"GOOD BUY":"WATCH"}</span></div><div class="hero-price">${money.format(i.lowest)}</div><div class="hero-sub">${i.qty_floor} available at this price</div><div class="metric-list">${p?`<div><span>Typical price</span><strong>${money.format(i.reference||0)}</strong></div><div><span>Discount</span><strong>${disc.toFixed(2)}%</strong></div>`:`<div><span>Estimated profit</span><strong>${money.format(profit)}</strong></div><div><span>ROI after fee</span><strong>${roi.toFixed(2)}%</strong></div><div><span>Total buy cost</span><strong>${money.format(i.floor_clear_capital||0)}</strong></div>`}<div><span>Next listing</span><strong>${i.next_higher?money.format(i.next_higher):"—"}</strong></div></div><button class="open-market" onclick="window.open('${i.market_url}','_blank','noopener')">Open Market</button></article>`}
function maybeSound(items){if(!sound.checked)return;const deals=items.filter(isDeal).sort((a,b)=>score(b)-score(a));if(!deals.length)return;const t=deals[0],k=`${t.id}:${t.lowest}:${Math.round(score(t))}`;if(k===lastAlertKey)return;lastAlertKey=k;try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.value=.04;o.start();o.stop(c.currentTime+.14)}catch{}}
function renderScan(d){const items=[...(d.items||[])].sort((a,b)=>score(b)-score(a)),deals=items.filter(isDeal);cards.innerHTML=items.length?items.map(card).join(""):`<div class="empty">Nothing selected.</div>`;dealCount.textContent=deals.length;if(deals.length){const b=deals[0];bestDeal.textContent=b.name;bestDealSub.textContent=b.mode==="stock"?`${b.discount_pct.toFixed(2)}% below typical price`:`${money.format(b.floor_clear_profit_after_fee)} estimated profit · ${b.net_roi_after_fee.toFixed(2)}% ROI`}else{bestDeal.textContent="None";bestDealSub.textContent="Nothing meets your buy settings right now"}lastUpdated.textContent=`Updated ${new Date(d.scanned_at*1000).toLocaleTimeString()}`;maybeSound(items)}
async function scanNow(){const ids=selectedIds();if(!ids.length)return msg("Select at least one item to watch.",true);saveSettings();scanBtn.disabled=true;scanBtn.textContent="Scanning…";try{const d=await call(`/api/scan?ids=${encodeURIComponent(ids.join(","))}`);renderScan(d);const e=(d.items||[]).filter(x=>x.error);msg(e.length?`Scan finished, but ${e.length} item(s) had an error.`:`Scanned ${d.items.length} item(s).`,!!e.length)}catch(e){msg(e.message,true)}finally{scanBtn.disabled=false;scanBtn.textContent="Scan Now"}}
function stopAuto(){if(timer)clearInterval(timer);timer=null;autoBtn.textContent="Start Auto Scan";autoBtn.classList.add("secondary")}
function toggleAuto(){if(timer)return stopAuto();saveSettings();scanNow();const s=Math.max(15,Number(interval.value||30));timer=setInterval(scanNow,s*1000);autoBtn.textContent=`Stop Auto Scan (${s}s)`;autoBtn.classList.remove("secondary")}
function renderLiquidity(items){if(!items.length){liquidityRows.innerHTML=`<tr><td colspan="7" class="muted">Run a few samples to start learning.</td></tr>`;return}liquidityRows.innerHTML=items.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.label||"Learning"}</td><td>${Number(x.score||0).toFixed(0)}</td><td>${x.observations||0}</td><td>${x.gap_events||0}</td><td>${Number(x.largest_gap_pct||0).toFixed(2)}%</td><td><button class="mini-btn" onclick="window.open('${x.market_url}','_blank','noopener')">Open</button></td></tr>`).join("")}
async function loadLiquidity(){try{const d=await call("/api/liquidity");renderLiquidity(d.items||[])}catch{}}
async function learnNow(){learnBtn.disabled=true;learnBtn.textContent="Sampling…";try{const d=await call("/api/learn",{method:"POST"});renderLiquidity(d.items||[]);learnUpdated.textContent=`Sampled ${new Date(d.learned_at*1000).toLocaleTimeString()}`;const e=(d.items||[]).filter(x=>x.error);if(e.length)msg(`Research sample completed with ${e.length} item error(s).`,true)}catch(e){msg(e.message,true)}finally{learnBtn.disabled=false;learnBtn.textContent="Sample Research Markets"}}
function stopLearnAuto(){if(learnTimer)clearInterval(learnTimer);learnTimer=null;learnAutoBtn.textContent="Start Quiet Learning";learnAutoBtn.classList.add("secondary")}
function toggleLearnAuto(){if(learnTimer)return stopLearnAuto();learnNow();learnTimer=setInterval(learnNow,120000);learnAutoBtn.textContent="Stop Quiet Learning (2m)";learnAutoBtn.classList.remove("secondary")}
function renderDiscovery(items){if(!items.length){discoverRows.innerHTML=`<tr><td colspan="8" class="muted">No discovery results.</td></tr>`;return}discoverRows.innerHTML=items.map(x=>{if(x.error)return`<tr><td><strong>${x.name}</strong></td><td colspan="6" class="bad">${x.error}</td><td></td></tr>`;const strong=x.kind==="NPC FLOOR"||x.kind==="UNDER MARKET";const potential=x.floor_profit>0?`${money.format(x.floor_profit)} guaranteed spread`:(x.discount_pct>=8?`${x.discount_pct.toFixed(1)}% under market`:"—");return`<tr class="${strong?"research-hit":""}"><td><strong>${x.name}</strong><br><small class="muted">${x.activity||"Learning"} · ${x.samples||0} samples</small></td><td><strong>${x.kind}</strong></td><td>${money.format(x.lowest||0)}${x.qty_floor>1?` × ${x.qty_floor}`:""}</td><td>${x.market_value?money.format(x.market_value):"—"}</td><td>${Number(x.discount_pct||0).toFixed(1)}%</td><td>${x.hard_floor?money.format(x.hard_floor):"—"}</td><td>${potential}</td><td><button class="mini-btn" onclick="window.open('${x.market_url}','_blank','noopener')">Open</button></td></tr>`}).join("")}
async function discoverNow(){discoverBtn.disabled=true;discoverBtn.textContent="Scanning…";try{const d=await call("/api/discover",{method:"POST"});renderDiscovery(d.items||[]);discoverUpdated.textContent=`Updated ${new Date(d.scanned_at*1000).toLocaleTimeString()}`;const hits=(d.items||[]).filter(x=>x.kind==="NPC FLOOR"||x.kind==="UNDER MARKET");msg(hits.length?`Hidden Deals found ${hits.length} interesting listing(s).`:`Hidden Deals checked the niche pool. No strong hits right now.`)}catch(e){msg(e.message,true)}finally{discoverBtn.disabled=false;discoverBtn.textContent="Scan Hidden Deals"}}
function stopDiscoverAuto(){if(discoverTimer)clearInterval(discoverTimer);discoverTimer=null;discoverAutoBtn.textContent="Auto Scan Hidden Deals";discoverAutoBtn.classList.add("secondary")}
function toggleDiscoverAuto(){if(discoverTimer)return stopDiscoverAuto();discoverNow();discoverTimer=setInterval(discoverNow,120000);discoverAutoBtn.textContent="Stop Hidden Auto Scan (2m)";discoverAutoBtn.classList.remove("secondary")}
["interval","minProfit","minRoi","stockDiscount","sound"].forEach(id=>document.addEventListener("change",e=>{if(e.target.id===id)saveSettings()}));key.addEventListener("keydown",e=>{if(e.key==="Enter")loadKey()});loadSavedSettings();status();